# Generated by Django 2.2 on 2019-07-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='product-thumbnails'),
        ),
        migrations.AlterField(
            model_name='userimage',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='user-thumbnails'),
        ),
    ]
